#!/bin/bash

#BSUB -P coral_omics
#BSUB -q bigmem
#BSUB -W 120:00
#BSUB -R "rusage[mem=12000]"
#BSUB -J dot_compare
#BSUB -n 4
#BSUB -e /scratch/projects/coral_omics/dot_comparison/ragtag_tamazonica_dot_compare.err
#BSUB -o /scratch/projects/coral_omics/dot_comparison/ragtag_tamazonica_dot_compare.out

# compare hifiasm assembly to tamazonica
# make the delta input file using nucmer
/nethome/mxd1288/software/local/quickmerge/MUMmer3.23/nucmer -l 100 -prefix Obeta_ragtag /scratch/projects/coral_omics/other_batrichoididae/thalassophryne_amazonica_genome.fna /scratch/projects/coral_omics/scaffolding/hifiasm_ragtag_output/hifiasm_ragtag_scaffold.fasta

DELTA=/scratch/projects/coral_omics/dot_comparison/Obeta_ragtag.delta

# prepare for dot using the .py script provided
~/software/local/dot/DotPrep.py --delta $DELTA

# then take the output *.coords and *.coords.idx and input here: https://dot.sandbox.bio/ 
