#!/bin/bash

#BSUB -P coral_omics
#BSUB -q bigmem
#BSUB -W 120:00
#BSUB -R "rusage[mem=20000]"
#BSUB -J tf_flye_pb
#BSUB -n 6
#BSUB -e /scratch/projects/coral_omics/flye_assembly/err_and_out/toadfish_flye_purged.err
#BSUB -o /scratch/projects/coral_omics/flye_assembly/err_and_out/toadfish_flye_purged.out

# this script will generate a consensus assembly from raw PacBio reads
# set variables
RAW_FASTQ=/scratch/projects/coral_omics/raw_reads/all.hifi_reads.fastq
OUT_DIR=/scratch/projects/coral_omics/flye_assembly
NUM_THREADS=6

# Run the assembly
# might need --pacbio-hifi OR --pacbio-raw (for CLR) OR --pacbio-corr for corrected raw CLR
flye --pacbio-hifi $RAW_FASTQ --genome-size 2.3g --resume-from consensus --out-dir $OUT_DIR --threads $NUM_THREADS

# Consensus keeps failing on it's own so try it like this
#flye-minimap2 '/projects/scratch/coral_omics/flye_assembly/00-assembly/draft_assembly.fasta' '/projects/scratch/coral_omics/raw_reads/all.hifi_reads.fastq' -x map-pb -t 10 -a -p 0.5 -N 10 --sam-hit-only -L -K 5G -z 1000 -Q --secondary-seq -I 64G | flye-samtools view -T '/projects/scratch/coral_omics/flye_assembly/00-assembly/draft_assembly.fasta' -u - | flye-samtools sort -T '/projects/scratch/coral_omics/flye_assembly/10-consensus/sort_220819_235712' -O bam -@ 4 -l 1 -m 32G -o '/projects/scratch/coral_omics/flye_assembly/10-consensus/minimap.bam'
#samtools mpileup -uf /projects/scratch/coral_omics/flye_assembly/00-assembly/draft_assembly.fasta /projects/scratch/coral_omics/flye_assembly/10-consensus/minimap.bam | bcftools call -c | vcfutils.pl vcf2fq > /projects/scratch/coral_omics/flye_assembly/10-consensus/consensus.fastq
#seqtk seq -aQ64 -q13 -n N /projects/scratch/coral_omics/flye_assembly/10-consensus/consensus.fastq > /projects/scratch/coral_omics/flye_assembly/10-consensus/consensus.fasta
