#!/bin/bash
#BSUB -n 24
#BSUB -J blast_parallel.job  
#BSUB -o blast_parallel.out
#BSUB -e blast_parallel.err
#BSUB -a openmpi
#BSUB -W 120:00
#BSUB -q parallel
#BSUB -P coral_omics

conda activate synema

module load openmpi-gcc/3.1.1
mpirun.lsf blastp -query Obeta_v1_pasa.assemblies.fasta.transdecoder.pep.complete_only.filtered \
-db refseq_protein_Jan2023/refseq_protein \
-max_target_seqs 25 \
-culling_limit 2 \
-num_threads 24 \
-evalue 1e-6 \
-outfmt 6 \
-out blastp.outfmt6
