#!/usr/bin/env bash

#BSUB -P coral_omics
#BSUB -J processreps
#BSUB -o processreps.out
#BSUB -e processreps.err
#BSUB -W 120:00
#BSUB -q general
#BSUB -n 5


PERL5LIB=~/mambaforge/envs/repeatmodeling/bin/perl
GENOME=fOpsBet2.1_genomic


# resummarize repeat compositions from combined analysis of all RepeatMasker rounds
ProcessRepeats -a -species actinopretygii 05_full_out/${GENOME}.full_mask.cat.gz 2>&1 | tee logs/05_fullmask.log

# calculate the length of the genome sequence in the FASTA
allLen=`seqtk comp ${GENOME}.fa | datamash sum 2`; 
# calculate the length of the N sequence in the FASTA
nLen=`seqtk comp ${GENOME}.fa | datamash sum 9`; 
# tabulate repeats per subfamily with total bp and proportion of genome masked
cat 05_full_out/${GENOME}.full_mask.out | tail -n +4 | awk -v OFS="\t" '{ print $6, $7, $11 }' | 
awk -F '[\t/]' -v OFS="\t" '{ if (NF == 3) print $3, "NA", $2 - $1 +1; else print $3, $4, $2 - $1 +1 }' | 
datamash -sg 1,2 sum 3 | grep -v "\?" | 
awk -v OFS="\t" -v genomeLen="${allLen}" '{ print $0, $4 / genomeLen }' > 05_full_out/${GENOME}.full_mask.tabulate
