#!/usr/bin/env bash

#BSUB -P coral_omics
#BSUB -J repclass_actinopterygii_job
#BSUB -o repclass_actinopterygii.out
#BSUB -e repclass_actinopterygii.err
#BSUB -W 120:00
#BSUB -q general
#BSUB -n 5


PERL5LIB=~/mambaforge/envs/repeatmodeling/bin/perl
GENOME=fOpsBet2.1_genomic


# classifying unknowns (-u): run with 5 threads/cores (-t) and using the Actinopterygii elements (-d) from Dfam 
# and known elements (-k) from the same reference genome; append newly identified elements to the existing known 
# element library (-a) and write results to an output directory (-o)
repclassifier -t 5 -d Actinopterygi -u ${GENOME}-families.prefix.fa.unknown \
-k ${GENOME}-families.prefix.fa.known -a ${GENOME}-families.prefix.fa.known \
-o round-1_DfamActinopterygii-Self


# classifying unknowns (-u): run with 5 threads/cores (-t) and using only the known elements (-k) from the 
# same reference genome; append newly identified elements to the existing known element library (-a) and 
# write results to an output directory (-o). No Dfam classification is used here.
repclassifier -t 5 -u round-1_DfamActinopterygii-Self/round-1_DfamActinopterygii-Self.unknown \
-k round-1_DfamActinopterygii-Self/round-1_DfamActinopterygii-Self.known \
-a round-1_DfamActinopterygii-Self/round-1_DfamActinopterygii-Self.known -o round-2_Self
