#!/bin/bash

#BSUB -n 4
#BSUB -J repclassifier
#BSUB -o repclassifier.out
#BSUB -e repclassifier.err
#BSUB -q debug
#BSUB -P coral_omics

conda activate repeatmodeling

# classifying unknowns (-u): run with 3 threads/cores (-t) and using the Actinopterygii elements (-d) from Dfam
# and known elements (-k) from the same reference genome; append newly identified elements to the existing known
# element library (-a) and write results to an output directory (-o)
repclassifier -t 3 -d Actinopterygii -u Obeta-families.prefix.fa.unknown \
-k Obeta-families.prefix.fa.known -a Obeta-families.prefix.fa.known \
-o round-1_DfamActinopterygii-Self
