#!/usr/bin/env bash

#BSUB -P coral_omics
#BSUB -J repmasker_round1
#BSUB -o repmasker_round1.out
#BSUB -e repmasker_round1.err
#BSUB -W 120:00
#BSUB -q general
#BSUB -n 15


PERL5LIB=~/mambaforge/envs/repeatmodeling/bin/perl
GENOME=fOpsBet2.1_genomic


# round 1: annotate/mask simple repeats
RepeatMasker -pa 15 \
-a \
-e ncbi \
-dir 01_simple_out \
-noint \
-xsmall \
../../assemblies/fOpsBet2.1_genomic.fa \
2>&1 | tee logs/01_simplemask.log

# round 1: rename outputs
rename fa simple_mask 01_simple_out/${GENOME}*
rename .masked .masked.fa 01_simple_out/${GENOME}*
